In [1]:
import pandas as pd

## Series Object

In [2]:
s = pd.Series([34,56,78,65,43])

In [3]:
s

0    34
1    56
2    78
3    65
4    43
dtype: int64

In [4]:
x = pd.Series([34,56,78,65,43,12.44])

In [5]:
x

0    34.00
1    56.00
2    78.00
3    65.00
4    43.00
5    12.44
dtype: float64

In [6]:
x[3]

65.0

In [7]:
x.size

6

In [8]:
x[3] = 10

In [9]:
x

0    34.00
1    56.00
2    78.00
3    10.00
4    43.00
5    12.44
dtype: float64

In [10]:
x = pd.Series([34,56,78,65,43,12.44], index= range(100,106))

In [11]:
x

100    34.00
101    56.00
102    78.00
103    65.00
104    43.00
105    12.44
dtype: float64

In [12]:
x[101]

56.0

## DataFrame Object

In [100]:
roll = pd.Series([1,2,3,4,5])
name = pd.Series(['Ajinkya', 'Riya', 'Natasha', 'Ravi', 'Virat'])
marks = pd.Series([56.65, 67.54, 67.54, 67.54, 85.55])
Class = pd.Series(['be','be','te','be','te'])

In [101]:
df1 = pd.DataFrame({
    'Roll': roll,
    'Name': name,
    'Marks': marks,
    'class': Class
})

In [102]:
df1

   Roll     Name  Marks class
0     1  Ajinkya  56.65    be
1     2     Riya  67.54    be
2     3  Natasha  67.54    te
3     4     Ravi  67.54    be
4     5    Virat  85.55    te

In [104]:
df1.sort_values(by=['Marks','class'])

   Roll     Name  Marks class
0     1  Ajinkya  56.65    be
1     2     Riya  67.54    be
3     4     Ravi  67.54    be
2     3  Natasha  67.54    te
4     5    Virat  85.55    te

In [16]:
df.shape

(5, 3)

In [17]:
df.size

15

In [18]:
df.columns

Index(['Roll', 'Name', 'Marks'], dtype='object')

In [19]:
pwd

'/home/aditya/Mitu Feb 2024'

### Download the dataset

In [20]:
# location: https://mitu.co.in/dataset
# download all the files starting from student

In [30]:
pwd

'/home/aditya/Mitu Feb 2024'

### Import the dataset

In [21]:
df = pd.read_csv('student.csv')

In [22]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [24]:
df = pd.read_csv('student1.csv')

In [25]:
df

    1     anil  TE  56.77  22
0   2     amit  TE  59.77  21
1   3   aniket  BE  76.88  19
2   4  ajinkya  TE  69.66  20
3   5     asha  TE  63.28  20
4   6   ayesha  BE  49.55  20
5   7     amar  BE  65.34  19
6   8    amita  BE  68.33  23
7   9     amol  TE  56.75  20
8  10    anmol  BE  78.66  21

In [26]:
headers = ['A', 'B', 'C', 'D', 'E']

In [27]:
df = pd.read_csv('student1.csv', names = headers)

In [28]:
df

    A        B   C      D   E
0   1     anil  TE  56.77  22
1   2     amit  TE  59.77  21
2   3   aniket  BE  76.88  19
3   4  ajinkya  TE  69.66  20
4   5     asha  TE  63.28  20
5   6   ayesha  BE  49.55  20
6   7     amar  BE  65.34  19
7   8    amita  BE  68.33  23
8   9     amol  TE  56.75  20
9  10    anmol  BE  78.66  21

In [32]:
# student3.tsv

df = pd.read_csv('student3.tsv', sep = '\t' )

In [33]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [34]:
df = pd.read_csv('student.csv')

In [35]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [36]:
df.shape

(10, 5)

In [37]:
df.size

50

In [39]:
list(df.columns)

['roll', 'name', 'class', 'marks', 'age']

In [40]:
df.T

,0,1,2,3,4,5,6,7,8,9
roll,1,2,3,4,5,6,7,8,9,10
name,anil,amit,aniket,ajinkya,asha,ayesha,amar,amita,amol,anmol
class,TE,TE,BE,TE,TE,BE,BE,BE,TE,BE
marks,56.77,59.77,76.88,69.66,63.28,49.55,65.34,68.33,56.75,78.66
age,22,21,19,20,20,20,19,23,20,21

In [42]:
df.dtypes

roll       int64
name      object
class     object
marks    float64
age        int64
dtype: object

In [43]:
df.values

array([[1, 'anil', 'TE', 56.77, 22],
       [2, 'amit', 'TE', 59.77, 21],
       [3, 'aniket', 'BE', 76.88, 19],
       [4, 'ajinkya', 'TE', 69.66, 20],
       [5, 'asha', 'TE', 63.28, 20],
       [6, 'ayesha', 'BE', 49.55, 20],
       [7, 'amar', 'BE', 65.34, 19],
       [8, 'amita', 'BE', 68.33, 23],
       [9, 'amol', 'TE', 56.75, 20],
       [10, 'anmol', 'BE', 78.66, 21]], dtype=object)

In [44]:
df.head(3)

   roll    name class  marks  age
0     1    anil    TE  56.77   22
1     2    amit    TE  59.77   21
2     3  aniket    BE  76.88   19

In [45]:
df.head()

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20

In [46]:
df.tail()

   roll    name class  marks  age
5     6  ayesha    BE  49.55   20
6     7    amar    BE  65.34   19
7     8   amita    BE  68.33   23
8     9    amol    TE  56.75   20
9    10   anmol    BE  78.66   21

In [47]:
df.tail(3)

   roll   name class  marks  age
7     8  amita    BE  68.33   23
8     9   amol    TE  56.75   20
9    10  anmol    BE  78.66   21

In [48]:
df.sum()

roll                                                    55
name     anilamitaniketajinkyaashaayeshaamaramitaamolanmol
class                                 TETEBETETEBEBEBETEBE
marks                                               644.99
age                                                    205
dtype: object

In [49]:
df.max()

roll         10
name     ayesha
class        TE
marks     78.66
age          23
dtype: object

In [50]:
df.min()

roll           1
name     ajinkya
class         BE
marks      49.55
age           19
dtype: object

In [52]:
df.count()

roll     10
name     10
class    10
marks    10
age      10
dtype: int64

In [53]:
df.describe()

           roll      marks        age
count  10.00000  10.000000  10.000000
mean    5.50000  64.499000  20.500000
std     3.02765   9.207179   1.269296
min     1.00000  49.550000  19.000000
25%     3.25000  57.520000  20.000000
50%     5.50000  64.310000  20.000000
75%     7.75000  69.327500  21.000000
max    10.00000  78.660000  23.000000

In [54]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

### Data Slicing

In [55]:
df.iloc[3:6,0:3]

   roll     name class
3     4  ajinkya    TE
4     5     asha    TE
5     6   ayesha    BE

In [56]:
df.iloc[3:,1:4]

      name class  marks
3  ajinkya    TE  69.66
4     asha    TE  63.28
5   ayesha    BE  49.55
6     amar    BE  65.34
7    amita    BE  68.33
8     amol    TE  56.75
9    anmol    BE  78.66

In [57]:
df.iloc[3:,1:]

      name class  marks  age
3  ajinkya    TE  69.66   20
4     asha    TE  63.28   20
5   ayesha    BE  49.55   20
6     amar    BE  65.34   19
7    amita    BE  68.33   23
8     amol    TE  56.75   20
9    anmol    BE  78.66   21

In [58]:
df.iloc[3,:4]

roll           4
name     ajinkya
class         TE
marks      69.66
Name: 3, dtype: object

In [59]:
df.iloc[[3,5,7],1:4]

      name class  marks
3  ajinkya    TE  69.66
5   ayesha    BE  49.55
7    amita    BE  68.33

In [60]:
df.iloc[:,1]

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5     ayesha
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [61]:
df.iloc[5,1]

'ayesha'

In [62]:
df.iloc[[1,4,5],[1,3]]

     name  marks
1    amit  59.77
4    asha  63.28
5  ayesha  49.55

In [63]:
df.loc[:,'name']

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5     ayesha
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [65]:
df.loc[3:,['name','marks']]

      name  marks
3  ajinkya  69.66
4     asha  63.28
5   ayesha  49.55
6     amar  65.34
7    amita  68.33
8     amol  56.75
9    anmol  78.66

In [75]:
df['name']

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5     ayesha
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [78]:
df[['name','class']]

      name class
0     anil    TE
1     amit    TE
2   aniket    BE
3  ajinkya    TE
4     asha    TE
5   ayesha    BE
6     amar    BE
7    amita    BE
8     amol    TE
9    anmol    BE

In [69]:
df.marks

0    56.77
1    59.77
2    76.88
3    69.66
4    63.28
5    49.55
6    65.34
7    68.33
8    56.75
9    78.66
Name: marks, dtype: float64

In [79]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [80]:
df.drop(4)

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [81]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [82]:
df.drop([4,6,8])

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
5     6   ayesha    BE  49.55   20
7     8    amita    BE  68.33   23
9    10    anmol    BE  78.66   21

In [84]:
df.drop('class', axis = 1)

   roll     name  marks  age
0     1     anil  56.77   22
1     2     amit  59.77   21
2     3   aniket  76.88   19
3     4  ajinkya  69.66   20
4     5     asha  63.28   20
5     6   ayesha  49.55   20
6     7     amar  65.34   19
7     8    amita  68.33   23
8     9     amol  56.75   20
9    10    anmol  78.66   21

In [85]:
df.drop(['name','marks'], axis = 1)

   roll class  age
0     1    TE   22
1     2    TE   21
2     3    BE   19
3     4    TE   20
4     5    TE   20
5     6    BE   20
6     7    BE   19
7     8    BE   23
8     9    TE   20
9    10    BE   21

### Renaming

In [86]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [87]:
cols = {'roll': 'id', 'marks':'grade'}

In [88]:
df.rename(columns= cols)

   id     name class  grade  age
0   1     anil    TE  56.77   22
1   2     amit    TE  59.77   21
2   3   aniket    BE  76.88   19
3   4  ajinkya    TE  69.66   20
4   5     asha    TE  63.28   20
5   6   ayesha    BE  49.55   20
6   7     amar    BE  65.34   19
7   8    amita    BE  68.33   23
8   9     amol    TE  56.75   20
9  10    anmol    BE  78.66   21

In [90]:
# rename index
# 1 => one,  4 => four

ind = {1: 'one', 4:'four'}
df.rename(index= ind)

      roll     name class  marks  age
0        1     anil    TE  56.77   22
one      2     amit    TE  59.77   21
2        3   aniket    BE  76.88   19
3        4  ajinkya    TE  69.66   20
four     5     asha    TE  63.28   20
5        6   ayesha    BE  49.55   20
6        7     amar    BE  65.34   19
7        8    amita    BE  68.33   23
8        9     amol    TE  56.75   20
9       10    anmol    BE  78.66   21

## Iteration

In [91]:
for x in df:
    print(x)

roll
name
class
marks
age

In [94]:
# use for loop and print all the columns i.e. values in cols

for x in df:
    print(df[x])

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: roll, dtype: int64
0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5     ayesha
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object
0    TE
1    TE
2    BE
3    TE
4    TE
5    BE
6    BE
7    BE
8    TE
9    BE
Name: class, dtype: object
0    56.77
1    59.77
2    76.88
3    69.66
4    63.28
5    49.55
6    65.34
7    68.33
8    56.75
9    78.66
Name: marks, dtype: float64
0    22
1    21
2    19
3    20
4    20
5    20
6    19
7    23
8    20
9    21
Name: age, dtype: int64

### sort the data

In [97]:
df.sort_values(by = 'marks')

   roll     name class  marks  age
5     6   ayesha    BE  49.55   20
8     9     amol    TE  56.75   20
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
4     5     asha    TE  63.28   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
3     4  ajinkya    TE  69.66   20
2     3   aniket    BE  76.88   19
9    10    anmol    BE  78.66   21

In [99]:
df.sort_values(by = ['marks','class'])

   roll     name class  marks  age
5     6   ayesha    BE  49.55   20
8     9     amol    TE  56.75   20
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
4     5     asha    TE  63.28   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
3     4  ajinkya    TE  69.66   20
2     3   aniket    BE  76.88   19
9    10    anmol    BE  78.66   21

In [105]:
df.sort_values(by = ['marks','class'], ascending= False)

   roll     name class  marks  age
9    10    anmol    BE  78.66   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
7     8    amita    BE  68.33   23
6     7     amar    BE  65.34   19
4     5     asha    TE  63.28   20
1     2     amit    TE  59.77   21
0     1     anil    TE  56.77   22
8     9     amol    TE  56.75   20
5     6   ayesha    BE  49.55   20

### Methods

In [106]:
df['marks'].sum()

644.9899999999999

In [107]:
df['marks'].min()

49.55

In [108]:
df['marks'].median()

64.31

### String Methods

In [113]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [114]:
df['name'].str.upper()

0       ANIL
1       AMIT
2     ANIKET
3    AJINKYA
4       ASHA
5     AYESHA
6       AMAR
7      AMITA
8       AMOL
9      ANMOL
Name: name, dtype: object

In [115]:
df['name'].str.title()

0       Anil
1       Amit
2     Aniket
3    Ajinkya
4       Asha
5     Ayesha
6       Amar
7      Amita
8       Amol
9      Anmol
Name: name, dtype: object

In [116]:
df['name'].str.len()

0    4
1    4
2    6
3    7
4    4
5    6
6    4
7    5
8    4
9    5
Name: name, dtype: int64

In [117]:
df['name'].str.startswith('an')

0     True
1    False
2     True
3    False
4    False
5    False
6    False
7    False
8    False
9     True
Name: name, dtype: bool

In [118]:
df['name'].str.endswith('a')

0    False
1    False
2    False
3     True
4     True
5     True
6    False
7     True
8    False
9    False
Name: name, dtype: bool

In [119]:
df['name'].str.repeat(3)

0             anilanilanil
1             amitamitamit
2       aniketaniketaniket
3    ajinkyaajinkyaajinkya
4             ashaashaasha
5       ayeshaayeshaayesha
6             amaramaramar
7          amitaamitaamita
8             amolamolamol
9          anmolanmolanmol
Name: name, dtype: object

### Add or modify

In [120]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [121]:
df['roll'] = df['roll'] + 100

In [122]:
df

   roll     name class  marks  age
0   101     anil    TE  56.77   22
1   102     amit    TE  59.77   21
2   103   aniket    BE  76.88   19
3   104  ajinkya    TE  69.66   20
4   105     asha    TE  63.28   20
5   106   ayesha    BE  49.55   20
6   107     amar    BE  65.34   19
7   108    amita    BE  68.33   23
8   109     amol    TE  56.75   20
9   110    anmol    BE  78.66   21

In [123]:
gender = ['m', 'm', 'm', 'm', 'f', 'f', 'm', 'f', 'm', 'm']

In [124]:
df['gender'] = gender

In [125]:
df

   roll     name class  marks  age gender
0   101     anil    TE  56.77   22      m
1   102     amit    TE  59.77   21      m
2   103   aniket    BE  76.88   19      m
3   104  ajinkya    TE  69.66   20      m
4   105     asha    TE  63.28   20      f
5   106   ayesha    BE  49.55   20      f
6   107     amar    BE  65.34   19      m
7   108    amita    BE  68.33   23      f
8   109     amol    TE  56.75   20      m
9   110    anmol    BE  78.66   21      m

In [126]:
# create a cgpa column => marks/10 + 1.05

df['cgpa'] = df['marks'] / 10 + 1.05

In [127]:
df

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  6.727
1   102     amit    TE  59.77   21      m  7.027
2   103   aniket    BE  76.88   19      m  8.738
3   104  ajinkya    TE  69.66   20      m  8.016
4   105     asha    TE  63.28   20      f  7.378
5   106   ayesha    BE  49.55   20      f  6.005
6   107     amar    BE  65.34   19      m  7.584
7   108    amita    BE  68.33   23      f  7.883
8   109     amol    TE  56.75   20      m  6.725
9   110    anmol    BE  78.66   21      m  8.916

In [129]:
df['gender'].value_counts()

gender
m    7
f    3
Name: count, dtype: int64

In [130]:
df['class'].value_counts()

class
TE    5
BE    5
Name: count, dtype: int64

In [131]:
df['gender'].mode()

0    m
Name: gender, dtype: object

In [132]:
df['class'].mode()

0    BE
1    TE
Name: class, dtype: object

In [136]:
df['class'].mode()[0]

'BE'

#### Grouping

In [138]:
df

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  6.727
1   102     amit    TE  59.77   21      m  7.027
2   103   aniket    BE  76.88   19      m  8.738
3   104  ajinkya    TE  69.66   20      m  8.016
4   105     asha    TE  63.28   20      f  7.378
5   106   ayesha    BE  49.55   20      f  6.005
6   107     amar    BE  65.34   19      m  7.584
7   108    amita    BE  68.33   23      f  7.883
8   109     amol    TE  56.75   20      m  6.725
9   110    anmol    BE  78.66   21      m  8.916

In [137]:
gr = df.groupby('class')

In [139]:
gr.get_group('TE')

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  6.727
1   102     amit    TE  59.77   21      m  7.027
3   104  ajinkya    TE  69.66   20      m  8.016
4   105     asha    TE  63.28   20      f  7.378
8   109     amol    TE  56.75   20      m  6.725

In [140]:
gr.groups

{'BE': [2, 5, 6, 7, 9], 'TE': [0, 1, 3, 4, 8]}

In [142]:
gr['marks'].agg(max)

/tmp/ipykernel_5557/1945279628.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  gr['marks'].agg(max)

class
BE    78.66
TE    69.66
Name: marks, dtype: float64

In [144]:
import numpy as np

In [145]:
gr['marks'].agg(np.mean)

/tmp/ipykernel_5557/299852483.py:1: FutureWarning: The provided callable <function mean at 0x742cf43dcf40> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  gr['marks'].agg(np.mean)

class
BE    67.752
TE    61.246
Name: marks, dtype: float64

In [147]:
gr['marks'].mean()

class
BE    67.752
TE    61.246
Name: marks, dtype: float64

### Concate the dataframes

In [148]:
df

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  6.727
1   102     amit    TE  59.77   21      m  7.027
2   103   aniket    BE  76.88   19      m  8.738
3   104  ajinkya    TE  69.66   20      m  8.016
4   105     asha    TE  63.28   20      f  7.378
5   106   ayesha    BE  49.55   20      f  6.005
6   107     amar    BE  65.34   19      m  7.584
7   108    amita    BE  68.33   23      f  7.883
8   109     amol    TE  56.75   20      m  6.725
9   110    anmol    BE  78.66   21      m  8.916

In [150]:
df.drop(['gender', 'cgpa'], axis = 1, inplace= True)

In [151]:
df

   roll     name class  marks  age
0   101     anil    TE  56.77   22
1   102     amit    TE  59.77   21
2   103   aniket    BE  76.88   19
3   104  ajinkya    TE  69.66   20
4   105     asha    TE  63.28   20
5   106   ayesha    BE  49.55   20
6   107     amar    BE  65.34   19
7   108    amita    BE  68.33   23
8   109     amol    TE  56.75   20
9   110    anmol    BE  78.66   21

In [153]:
# create a dataframe of columns gender, cgpa, roll
# this roll column will be the same as of roll column of df
gender = ['m', 'm', 'm', 'm', 'f', 'f', 'm', 'f', 'm', 'm']
cgpa = df['marks'] / 10 + 1.05

newdf = pd.DataFrame({
    'roll':range(101,111),
    'gender': gender,
    'cgpa': cgpa
})

In [154]:
newdf

   roll gender   cgpa
0   101      m  6.727
1   102      m  7.027
2   103      m  8.738
3   104      m  8.016
4   105      f  7.378
5   106      f  6.005
6   107      m  7.584
7   108      f  7.883
8   109      m  6.725
9   110      m  8.916

In [155]:
df

   roll     name class  marks  age
0   101     anil    TE  56.77   22
1   102     amit    TE  59.77   21
2   103   aniket    BE  76.88   19
3   104  ajinkya    TE  69.66   20
4   105     asha    TE  63.28   20
5   106   ayesha    BE  49.55   20
6   107     amar    BE  65.34   19
7   108    amita    BE  68.33   23
8   109     amol    TE  56.75   20
9   110    anmol    BE  78.66   21

In [156]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [157]:
newdf.columns

Index(['roll', 'gender', 'cgpa'], dtype='object')

In [158]:
# merge

pd.merge(df, newdf, on = 'roll')

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  6.727
1   102     amit    TE  59.77   21      m  7.027
2   103   aniket    BE  76.88   19      m  8.738
3   104  ajinkya    TE  69.66   20      m  8.016
4   105     asha    TE  63.28   20      f  7.378
5   106   ayesha    BE  49.55   20      f  6.005
6   107     amar    BE  65.34   19      m  7.584
7   108    amita    BE  68.33   23      f  7.883
8   109     amol    TE  56.75   20      m  6.725
9   110    anmol    BE  78.66   21      m  8.916

In [ ]:
# Concate

In [161]:
new = pd.read_csv('student5.csv')
new

   roll     name class  marks  age
0     1   surbhi    TE  67.44   23
1     2    sujay    TE  74.12   22
2     3  subhash    BE  82.44   21
3     4   sachin    TE  59.33   21
4     5  shalini    TE  63.45   20

In [162]:
df

   roll     name class  marks  age
0   101     anil    TE  56.77   22
1   102     amit    TE  59.77   21
2   103   aniket    BE  76.88   19
3   104  ajinkya    TE  69.66   20
4   105     asha    TE  63.28   20
5   106   ayesha    BE  49.55   20
6   107     amar    BE  65.34   19
7   108    amita    BE  68.33   23
8   109     amol    TE  56.75   20
9   110    anmol    BE  78.66   21

In [165]:
pd.concat([df, new], ignore_index= True)

    roll     name class  marks  age
0    101     anil    TE  56.77   22
1    102     amit    TE  59.77   21
2    103   aniket    BE  76.88   19
3    104  ajinkya    TE  69.66   20
4    105     asha    TE  63.28   20
5    106   ayesha    BE  49.55   20
6    107     amar    BE  65.34   19
7    108    amita    BE  68.33   23
8    109     amol    TE  56.75   20
9    110    anmol    BE  78.66   21
10     1   surbhi    TE  67.44   23
11     2    sujay    TE  74.12   22
12     3  subhash    BE  82.44   21
13     4   sachin    TE  59.33   21
14     5  shalini    TE  63.45   20