In [2]:
# Data=> Social_Network_Ads.csv

In [21]:
import pandas as pd
import numpy as mp
import matplotlib.pyplot as plt

In [23]:
df = pd.read_csv('Social_Network_Ads.csv')
df.head()

    User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510    Male  19.0          19000.0          0
1  15810944    Male  35.0          20000.0          0
2  15668575  Female  26.0          43000.0          0
3  15603246  Female  27.0          57000.0          0
4  15804002    Male  19.0          76000.0          0

In [25]:
newdf = df.copy()

In [27]:
newdf.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [29]:
newdf.dtypes

User ID              int64
Gender              object
Age                float64
EstimatedSalary    float64
Purchased            int64
dtype: object

# Label Encoding

In [32]:
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
newdf['Gender'] = enc.fit_transform(newdf['Gender'])

In [34]:
newdf

      User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510       1  19.0          19000.0          0
1    15810944       1  35.0          20000.0          0
2    15668575       0  26.0          43000.0          0
3    15603246       0  27.0          57000.0          0
4    15804002       1  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863       0  46.0          41000.0          1
396  15706071       1  51.0          23000.0          1
397  15654296       0  50.0          20000.0          1
398  15755018       1  36.0          33000.0          0
399  15594041       0  49.0          36000.0          1

[400 rows x 5 columns]

# One Hot Encoding

In [39]:
pd.get_dummies(df)

      User ID   Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0    15624510  19.0          19000.0          0          False         True
1    15810944  35.0          20000.0          0          False         True
2    15668575  26.0          43000.0          0           True        False
3    15603246  27.0          57000.0          0           True        False
4    15804002  19.0          76000.0          0          False         True
..        ...   ...              ...        ...            ...          ...
395  15691863  46.0          41000.0          1           True        False
396  15706071  51.0          23000.0          1          False         True
397  15654296  50.0          20000.0          1           True        False
398  15755018  36.0          33000.0          0          False         True
399  15594041  49.0          36000.0          1           True        False

[400 rows x 6 columns]